services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: tennisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  kafka:
#  kafka:
#    image: confluentinc/cp-kafka:7.6.0
#    container_name: kafka
#    ports:
#      - "9092:9092"    # Client connections
#      - "9093:9093"    # Controller communication
#    environment:
#      KAFKA_KRAFT_MODE: "true"
#      KAFKA_PROCESS_ROLES: "broker,controller"
#      KAFKA_NODE_ID: 1
#
#      CLUSTER_ID: 8ij5bJvfRReWRnuaO7XPXw
#
#      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_LOG_DIRS: /var/lib/kafka/data
#    volumes:
#      - kafka-data:/var/lib/kafka/data
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: "1"
      CLUSTER_ID: 8ij5bJvfRReWRnuaO7XPXw
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - 9092:9092
    networks:
      - kafka-net
  backend:
    build: ./tennisGameBackend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tennisdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka-net

  frontend:
    build: ./tennisGameFrontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  kafka-data:

networks:
  kafka-net: